name: Generate CLOC Badge

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate CLOC Badge
      uses: Nightfury874/generate-cloc-badge-action@version-1.0.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
